### ISSUE TITLE
Error while converting

### ISSUE THREAD

**Issue by OesieGIT** [mariush444/gmapIcons2osmand#2]
When there are 'special' letters in Google Maps the script will give the below error. After changing all the 'special' letters the script worked.

`python kmz2osmand.py "POI.kmz" > Test3.gpx
Traceback (most recent call last):
  File "C:\Users\USR\Downloads\kmz2osmand.py", line 352, in <module>
    parser.parse(open(input,"r"))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\xml\sax\expatreader.py", line 105, in parse
    xmlreader.IncrementalParser.parse(self, source)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\xml\sax\xmlreader.py", line 123, in parse
    while buffer := file.read(self._bufsize):
                    ~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 32305: character maps to <undefined>`

**Comment by mariush444** [comment]
Can you attatch you kmz file?

**Comment by OesieGIT** [comment]
> Can you attatch you kmz file?

You are quick! I just edited my first post before I saw your reaction. It has to do with the 'special' characters (ă , â , ê , ô , ơ , ư , đ) being used in the i.e. the Vietnames language (and probably other charactes aswell). After I removed those it worked.

**Comment by mariush444** [comment]
Aren't they in utf8 coded?
It should work with utf8.
May try to verify page code in windows command line?

**Comment by OesieGIT** [comment]
> Aren't they in utf8 coded? It should work with utf8. May try to verify page code in windows command line?

No idea how Google Maps code the names. When I edited the names (removed the special characters) in Google Maps, export to kmz and run your script it was good to go. The other project I found (https://github.com/tmusolf/GoogleMapToOSMAndGPX) has the same issue.

**Comment by mariush444** [comment]
yes, tmusolf makes good job.
I try to make a list (hub)  tools for osmand.
If you find something interesting in the future, let me know please.

https://github.com/mariush444/Osmand-tools/blob/main/README.md
